### ISSUE TITLE
How can this be used with three.js?

### ISSUE THREAD

**Issue by TheCodeDestroyer** [expo/expo-gl#5]
I tried using `expo-three` library but it seems to depend on `expo` module, getting this error:
```
Unable to resolve module `expo` from `/node_modules/expo-three/lib/AR/index.js`: Module `expo` does not exist in the Haste module map
```

Any help would be appreciated!

**Comment by tsapeta** [comment]
Hey @TheCodeDestroyer,
Right now `expo-three` is not working in vanilla React Native apps without Expo. That's because `expo-three` still depends on the whole `expo` package instead of universal modules.

@EvanBacon are you planning to add support in `expo-three` for such apps? Is it possible yet? I guess no as `AR` is still bundled in `expo` package.

**Comment by TheCodeDestroyer** [comment]
@tsapeta is there a way to load textures or models without expo-three using just three.js and expo-gl?

**Comment by bbarthec** [comment]
@TheCodeDestroyer if you're using **expo-three** just to load some textures than you can easily extract some code from library and adjust it by removing **expo** dependency.
As far as I know **expo** dependency is no longer needed, because we've extracted one module that is being used during texture loading to separate library (see [here](https://www.npmjs.com/package/expo-asset)).
To achieve what you're asking for, you need to copy some code from **expo-three** and replace `import { SomeModule } from 'expo'` with `import { someFunction } from 'some-expo-module'`. ([`expo-asset` example](https://github.com/expo/expo-three/blob/master/lib/resolveAsset/index.native.js) would go like this: `import { Asset } from 'expo-asset`)

**Comment by TheCodeDestroyer** [comment]
@bbarthec thank you I will try to reverse engineering it again, maybe I missed something the last time.
